import {
  BadgeCheck,
  Building2,
  CalendarX,
  CircleCheck,
  CircleDashed,
  CircleMinus,
  Clock,
  Database,
  EyeOff,
  FileText,
  Gauge,
  Globe,
  History,
  Lightbulb,
  Lock,
  Replace,
  ShieldAlert,
  ShieldCheck,
  ShieldX,
  TriangleAlert,
  type LucideIcon,
} from "lucide-react";

import { Badge } from "@/components/ui/badge";
import type {
  EmbeddingStatus,
  Freshness,
  MemoryOrigin,
  Sensitivity,
  SourceTier,
  TrustRank,
  VerificationState,
} from "@/domain/memory/types";
import { cn } from "@/lib/utils";

/**
 * Every operational state is rendered as an icon beside its own words. Colour
 * is a secondary cue only: a reader who cannot distinguish the tones still gets
 * the whole meaning from the label, which is what makes the console safe to act
 * on.
 */
export function StatusLabel({
  label,
  icon: Icon,
  prefix,
  className,
}: {
  label: string;
  icon: LucideIcon;
  prefix?: string;
  className?: string;
}) {
  return (
    <Badge
      variant="outline"
      data-testid={`memory-status-${label.toLowerCase().replace(/\s+/g, "-")}`}
      className={cn("gap-1 font-normal", className)}
    >
      <Icon aria-hidden="true" className="size-3" />
      {prefix ? <span className="text-muted-foreground">{prefix}</span> : null}
      <span>{label}</span>
    </Badge>
  );
}

const verificationLabels: Readonly<
  Record<VerificationState, { label: string; icon: LucideIcon; className: string }>
> = {
  verified: { label: "Verified", icon: ShieldCheck, className: "text-success" },
  unverified: { label: "Unverified", icon: ShieldAlert, className: "text-foreground" },
  proposed: { label: "Proposed", icon: CircleDashed, className: "text-foreground" },
  rejected: { label: "Rejected", icon: ShieldX, className: "text-destructive" },
};

const freshnessLabels: Readonly<
  Record<Freshness, { label: string; icon: LucideIcon; className: string }>
> = {
  fresh: { label: "Fresh", icon: CircleCheck, className: "text-success" },
  aging: { label: "Review due soon", icon: Clock, className: "text-foreground" },
  stale: { label: "Review overdue", icon: History, className: "text-foreground" },
  superseded: { label: "Superseded", icon: Replace, className: "text-muted-foreground" },
  expired: { label: "Expired", icon: CalendarX, className: "text-destructive" },
};

const sensitivityLabels: Readonly<Record<Sensitivity, { label: string; icon: LucideIcon }>> = {
  public: { label: "Public", icon: Globe },
  internal: { label: "Internal", icon: Building2 },
  confidential: { label: "Confidential", icon: Lock },
  customer_content: { label: "Customer content", icon: EyeOff },
};

const embeddingLabels: Readonly<Record<EmbeddingStatus, { label: string; icon: LucideIcon }>> = {
  ready: { label: "Embedded", icon: CircleCheck },
  pending: { label: "Embedding pending", icon: Clock },
  failed: { label: "Embedding failed", icon: TriangleAlert },
  skipped: { label: "Embedding skipped", icon: CircleMinus },
};

const originLabels: Readonly<Record<MemoryOrigin, string>> = {
  user_verified: "Entered by a person",
  provider_imported: "Imported from a provider",
  system_generated: "Generated by the platform",
  ai_proposed: "Proposed by a model",
  outcome_learned: "Learned from an outcome",
};

/**
 * The five trust ranks from `context/09-business-memory.md`, named in the words
 * the ordering actually means. Retrieval sorts by this rank before relevance,
 * so the group heading is the reader's explanation of the result order.
 */
export const trustRankGroups: Readonly<
  Record<TrustRank, { label: string; description: string; icon: LucideIcon }>
> = {
  0: {
    label: "Verified — first-party source",
    description: "A person confirmed this against a first-party source.",
    icon: ShieldCheck,
  },
  1: {
    label: "Verified or direct input",
    description: "Confirmed knowledge, or stated directly by someone in the business.",
    icon: BadgeCheck,
  },
  2: {
    label: "Current provider record",
    description: "Unconfirmed system-of-record data that is still within its review date.",
    icon: Database,
  },
  3: {
    label: "Document or historical record",
    description: "An approved document, or provider data past its review date.",
    icon: FileText,
  },
  4: {
    label: "Unverified inference",
    description: "Model-authored inference. Treat as a lead, not as fact.",
    icon: Lightbulb,
  },
};

export function VerificationLabel({ state }: { state: VerificationState }) {
  const entry = verificationLabels[state];
  return <StatusLabel label={entry.label} icon={entry.icon} className={entry.className} />;
}

export function FreshnessLabel({ freshness }: { freshness: Freshness }) {
  const entry = freshnessLabels[freshness];
  return <StatusLabel label={entry.label} icon={entry.icon} className={entry.className} />;
}

export function SensitivityLabel({ sensitivity }: { sensitivity: Sensitivity }) {
  const entry = sensitivityLabels[sensitivity];
  return <StatusLabel label={entry.label} icon={entry.icon} />;
}

export function EmbeddingLabel({ status }: { status: string }) {
  const entry = embeddingLabels[status as EmbeddingStatus];
  return entry ? <StatusLabel label={entry.label} icon={entry.icon} /> : null;
}

export function SourceLabel({
  origin,
  sourceTier,
  sourceSystem,
}: {
  origin: string;
  sourceTier: SourceTier | number;
  sourceSystem?: string;
}) {
  const originLabel = originLabels[origin as MemoryOrigin] ?? origin;
  return (
    <StatusLabel
      label={sourceSystem ?? originLabel}
      prefix={`Source · tier ${sourceTier} ·`}
      icon={Database}
    />
  );
}

export function ConfidenceLabel({ confidence }: { confidence?: number }) {
  if (confidence === undefined) return null;
  return <StatusLabel label={`Confidence ${Math.round(confidence * 100)}%`} icon={Gauge} />;
}

export type KnowledgeState = "recorded" | "suggested" | "planned" | "measured" | "reviewed";

const knowledgeStateLabels: Readonly<Record<KnowledgeState, { label: string; icon: LucideIcon }>> = {
  recorded: { label: "Recorded", icon: Database },
  suggested: { label: "Suggested", icon: Lightbulb },
  planned: { label: "Planned", icon: Clock },
  measured: { label: "Measured", icon: Gauge },
  reviewed: { label: "Reviewed", icon: ShieldCheck },
};

/**
 * The plain-words state of one memory item (Spec 023 §13 timeline copy).
 *
 * Derived from the stored memory type, origin, and verification state only —
 * never from body text. Captured source projections read as recorded
 * observations, model-proposed episodes as suggestions, operator decisions as
 * plans, settled outcomes as measurements, and human-verified lessons as
 * reviewed. Manual notes, documents, projected facts, and fact proposals carry
 * no state label: they are workspace content or pending changes, not captured
 * knowledge, and labelling them would imply a lineage they do not have.
 */
export function knowledgeStateFor(input: {
  memoryType: string;
  origin: string;
  verificationState: string;
}): KnowledgeState | null {
  if (input.memoryType === "outcome") return "measured";
  if (input.memoryType === "decision") return "planned";
  if (input.memoryType === "lesson")
    return input.verificationState === "verified" ? "reviewed" : "suggested";
  if (input.memoryType === "episode")
    return input.origin === "ai_proposed" ? "suggested" : "recorded";
  return null;
}

export function KnowledgeStateLabel({
  memoryType,
  origin,
  verificationState,
}: {
  memoryType: string;
  origin: string;
  verificationState: string;
}) {
  const state = knowledgeStateFor({ memoryType, origin, verificationState });
  if (!state) return null;
  const entry = knowledgeStateLabels[state];
  return <StatusLabel label={entry.label} icon={entry.icon} />;
}

/**
 * Captured source projections are read-only downstream: the owning feature
 * stays authoritative, so a correction belongs at the source, not on the
 * memory copy. Rendered only when the item names its source system — manual
 * notes have no source to point at, and inventing one would mislead.
 */
export function SourceCorrectionNote({
  sourceSystem,
  sourceReference,
}: {
  sourceSystem?: string;
  sourceReference?: string;
}) {
  if (!sourceSystem) return null;
  return (
    <p className="text-[11px] text-muted-foreground">
      Corrections happen at the source. Open source: {sourceSystem}
      {sourceReference ? ` · Ref: ${sourceReference}` : ""}.
    </p>
  );
}

/**
 * The provenance strip shared by result cards and the inspection Dialog.
 * Embedding state is optional because a retrieval result does not carry it; it
 * is only known once the item detail has been read.
 */
export function ProvenanceBadges({
  verificationState,
  freshness,
  sensitivity,
  origin,
  sourceTier,
  sourceSystem,
  confidence,
  embeddingStatus,
}: {
  verificationState: VerificationState;
  freshness: Freshness;
  sensitivity: Sensitivity;
  origin: string;
  sourceTier: SourceTier | number;
  sourceSystem?: string;
  confidence?: number;
  embeddingStatus?: string;
}) {
  return (
    <div className="flex flex-wrap items-center gap-1.5">
      <VerificationLabel state={verificationState} />
      <FreshnessLabel freshness={freshness} />
      <SensitivityLabel sensitivity={sensitivity} />
      <SourceLabel origin={origin} sourceTier={sourceTier} sourceSystem={sourceSystem} />
      <ConfidenceLabel confidence={confidence} />
      {embeddingStatus ? <EmbeddingLabel status={embeddingStatus} /> : null}
    </div>
  );
}
