const { chromium } = require('@playwright/test');
const assert = require('node:assert/strict');
const path = require('node:path');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1080}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('file://'+path.join(__dirname,'prototype.html'),{waitUntil:'domcontentloaded'});
 await page.evaluate(()=>document.fonts.ready);
 const checks=[];const check=(label,value)=>{assert.ok(value,label);checks.push(label)};
 check('February totals match coverage', (await page.locator('#stats').innerText()).includes('138,000')&&(await page.locator('#stats').innerText()).includes('114,000'));
 await page.getByRole('button',{name:'Share',exact:true}).click();
 check('Share is derived from reported total',(await page.locator('#chart').innerText()).includes('58.0%'));
 await page.getByRole('button',{name:'Amount',exact:true}).click();
 await page.getByRole('combobox',{name:'Reporting period'}).selectOption('jan');
 check('Period updates totals and list',(await page.locator('#stats').innerText()).includes('117,000')&&(await page.locator('#rows').innerText()).includes('70,000'));
 await page.getByRole('combobox',{name:'Reporting period'}).selectOption('feb');
 await page.getByRole('button',{name:'Needs attention 2',exact:true}).click();
 check('Attention filter shows two channels',await page.locator('#rows tr').count()===2);
 check('Directory filter leaves portfolio unchanged',(await page.locator('#stats').innerText()).includes('138,000'));
 await page.getByRole('searchbox').fill('no matching channel');check('Search empty state visible',await page.locator('#empty').isVisible());
 await page.getByRole('button',{name:'Clear filters',exact:true}).click();
 await page.getByRole('button',{name:'Review data coverage',exact:true}).click();
 check('Coverage dialog opens',await page.getByRole('dialog').isVisible());
 await page.keyboard.press('Escape');check('Escape closes dialog',!await page.getByRole('dialog').isVisible());
 await page.getByRole('button',{name:'Channel Audit',exact:true}).first().click();
 check('Audit page remains excluded',(await page.getByRole('dialog').innerText()).includes('outside this redesign'));
 await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Add channel',exact:true}).click();
 await page.getByLabel('Channel name',{exact:true}).fill('Test <channel>');
 await page.getByRole('button',{name:'Add to preview',exact:true}).click();
 check('Local add renders escaped name',(await page.locator('#rows').innerText()).includes('Test <channel>'));
 check('New channel has no invented revenue',(await page.locator('#stats').innerText()).includes('138,000'));
 await page.getByRole('button',{name:'Manage Test <channel>',exact:true}).click();
 await page.getByLabel('Channel name',{exact:true}).fill('Test edited');
 await page.getByRole('button',{name:'Save preview changes',exact:true}).click();
 check('Edit updates directory',(await page.locator('#rows').innerText()).includes('Test edited'));
 await page.getByRole('button',{name:'Manage Test edited',exact:true}).click();
 await page.getByRole('button',{name:'Archive channel',exact:true}).click();
 await page.getByRole('button',{name:'Archive',exact:true}).click();
 check('Archived channel leaves active list',!(await page.locator('#rows').innerText()).includes('Test edited'));
 await page.getByRole('button',{name:'Archived 2',exact:true}).click();
 await page.getByRole('button',{name:'Manage Test edited',exact:true}).click();
 await page.getByRole('button',{name:'Restore channel',exact:true}).click();
 await page.getByRole('button',{name:'Restore',exact:true}).click();
 await page.getByRole('button',{name:'Active 5',exact:true}).click();
 check('Restore returns channel to active list',(await page.locator('#rows').innerText()).includes('Test edited'));
 await page.reload({waitUntil:'domcontentloaded'});await page.evaluate(()=>document.fonts.ready);
 check('Reload resets prototype changes',await page.locator('#rows tr').count()===4);
 await page.getByRole('button',{name:'Sort channels by reported revenue'}).click();
 check('Revenue sort works',(await page.locator('#rows tr').first().innerText()).includes('Direct'));
 await page.getByRole('button',{name:'Sort channels by reported revenue'}).click();
 check('No desktop horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.evaluate(()=>scrollTo(0,0));
 await page.screenshot({path:path.join(__dirname,'desktop.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});
 check('No mobile horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 check('Mobile shows readable channel cards',await page.locator('#rows tr').first().evaluate(e=>getComputedStyle(e).display)==='grid');
 await page.screenshot({path:path.join(__dirname,'mobile.png'),fullPage:true});
 await page.getByRole('button',{name:'Toggle navigation',exact:true}).click();check('Mobile navigation opens',await page.locator('#sidebar').isVisible());
 await page.keyboard.press('Escape');check('Mobile navigation closes',!await page.locator('#sidebar').isVisible());
 await page.getByRole('button',{name:'Add channel',exact:true}).click();check('Mobile dialog fits viewport',await page.getByRole('dialog').evaluate(e=>e.getBoundingClientRect().width<=innerWidth));
 await page.keyboard.press('Escape');
 await page.setViewportSize({width:320,height:760});
 check('No narrow mobile overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.setViewportSize({width:768,height:1024});
 check('No tablet overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.evaluate(()=>{channels.forEach(c=>c.archived=true);render()});
 check('Empty portfolio does not invent zero revenue',!(await page.locator('#stats').innerText()).includes('AED'));
 check('No JavaScript runtime errors',errors.length===0);
 require('node:fs').writeFileSync(path.join(__dirname,'verification.json'),JSON.stringify({checks,passed:checks.length,errors,viewports:['1440x1080','390x844','320x760','768x1024']},null,2)+'\n');
 console.log(`${checks.length} prototype checks passed; desktop and mobile screenshots saved.`);await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
