const {chromium}=require('@playwright/test');
const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');
(async()=>{const browser=await chromium.launch();const page=await browser.newPage();
const file=path.resolve(__dirname,'../prototype.html');const selectors=['.heading','.heading h1','.heading p','#add-channel','.toolbar','.scope-control','.statstrip','.stat','.stat-label','.stat-value','.stat-note','.compare-card','.comparison','.plot','.plot-head','.segmented','.legend','.chart-row','.chart-name','.chart-track','.bar','.chart-value','.axis','.chart-footer','.coverage','.coverage-big','.coverage-blocks','.coverage-line','#coverage-detail','.insight-note','.directory','.directory-heading','.directory-tools','.filters','.filters button','.search','.table-wrap','th','td','.channel-icon','.channel-name','.channel-sub','.pill','.row-actions','.audit-btn','.menu-btn','.table-foot','.pagefoot'];
const result={prototypeSha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),viewports:[],dialogs:[],symbols:[]};
for(const width of [1440,1200,980,768,650,390,320]){await page.setViewportSize({width,height:1080});await page.goto('file://'+file,{waitUntil:'domcontentloaded'});await Promise.race([page.evaluate(()=>document.fonts.ready),new Promise(r=>setTimeout(r,4000))]);
result.viewports.push(await page.evaluate(({selectors,width})=>({width,rootWidth:document.documentElement.scrollWidth,font:document.fonts.check('13px Manrope'),sections:selectors.map(selector=>{const e=document.querySelector(selector);if(!e)return{selector,missing:true};const s=getComputedStyle(e),r=e.getBoundingClientRect();return{selector,text:e.textContent.trim().slice(0,220),box:{x:r.x,y:r.y,width:r.width,height:r.height},styles:Object.fromEntries(['display','grid-template-columns','gap','font-family','font-size','font-weight','line-height','letter-spacing','color','background-color','border-radius','padding','margin','border','height','min-height','width','max-width'].map(k=>[k,s.getPropertyValue(k)]))}}),controls:[...document.querySelectorAll('button,a,input,select')].filter(e=>e.getClientRects().length).map(e=>({tag:e.tagName,text:e.textContent.trim(),id:e.id,ariaLabel:e.getAttribute('aria-label'),href:e.getAttribute('href'),pressed:e.getAttribute('aria-pressed'),icons:[...e.querySelectorAll('use')].map(u=>u.getAttribute('href'))}))}),{selectors,width}));}
await page.setViewportSize({width:1440,height:1080});await page.reload({waitUntil:'domcontentloaded'});
for(const [name,selector]of [['reporting-window','#scope-detail'],['coverage','#coverage-detail'],['setup-help','#setup-help'],['create','#add-channel'],['manage','[data-edit="a"]'],['audit-boundary','[data-audit="a"]']]){await page.locator(selector).click();result.dialogs.push(await page.locator('#dialog').evaluate((e,name)=>({name,text:e.innerText,box:{width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height},controls:[...e.querySelectorAll('button,input,select')].map(c=>({tag:c.tagName,text:c.textContent.trim(),id:c.id,type:c.getAttribute('type'),value:c.value,icons:[...c.querySelectorAll('use')].map(u=>u.getAttribute('href'))}))}),name));await page.screenshot({path:path.join(__dirname,name+'.png')});await page.keyboard.press('Escape');}
await page.locator('[data-edit="a"]').click();await page.locator('#archive-channel').click();await page.screenshot({path:path.join(__dirname,'archive-confirmation.png')});result.dialogs.push({name:'archive-confirmation',text:await page.locator('#dialog').innerText()});await page.keyboard.press('Escape');
result.symbols=await page.locator('symbol').evaluateAll(es=>es.map(e=>({id:e.id,viewBox:e.getAttribute('viewBox'),svg:e.innerHTML})));
fs.writeFileSync(path.join(__dirname,'visual-inventory.json'),JSON.stringify(result,null,2)+'\n');fs.writeFileSync(path.join(__dirname,'prototype-reference.css'),fs.readFileSync(file,'utf8').match(/<style>([\s\S]*?)<\/style>/)[1]);
console.log('Captured '+result.viewports.length+' viewport inventories, '+result.dialogs.length+' dialogs, '+result.symbols.length+' SVG symbols.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
