import { CircleAlert, Clock3, Plus, Sparkles } from "lucide-react";
import { StatusBadge } from "@/components/ui/status-badge";

export default function OverviewPage() {
  return <div className="space-y-10"><section className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-sm font-medium text-accent">Friday, 7 August 2026</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Good morning, operator.</h2><p className="mt-2 max-w-xl text-muted-foreground">A calm view of what needs attention across your client portfolio.</p></div><button disabled title="Available with the Organization + Digital Twin onboarding slice" type="button" className="inline-flex cursor-not-allowed items-center justify-center gap-2 rounded-lg bg-foreground px-4 py-2.5 text-sm font-semibold text-background opacity-50"><Plus size={16} />Create organization</button></section>
    <section className="grid gap-4 md:grid-cols-3"><div className="rounded-xl border border-border bg-surface p-5"><div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">Organizations</p><StatusBadge label="Foundation" /></div><p className="mt-5 text-3xl font-semibold">0</p><p className="mt-1 text-sm text-muted-foreground">No clients onboarded yet</p></div><div className="rounded-xl border border-border bg-surface p-5"><p className="text-sm text-muted-foreground">Opportunities requiring review</p><p className="mt-5 text-3xl font-semibold">—</p><p className="mt-1 text-sm text-muted-foreground">Recommendations appear after onboarding</p></div><div className="rounded-xl border border-border bg-surface p-5"><p className="text-sm text-muted-foreground">Execution health</p><p className="mt-5 text-3xl font-semibold">Ready</p><p className="mt-1 text-sm text-muted-foreground">No workflows have run</p></div></section>
    <section className="grid gap-6 lg:grid-cols-[1.4fr_1fr]"><div className="rounded-xl border border-border bg-surface"><div className="flex items-center justify-between border-b border-border px-6 py-5"><div><h3 className="font-semibold">What needs attention</h3><p className="mt-1 text-sm text-muted-foreground">Prioritized by impact, confidence, and urgency.</p></div><Sparkles size={19} className="text-accent" /></div><div className="flex min-h-64 flex-col items-center justify-center px-6 text-center"><div className="mb-4 flex size-11 items-center justify-center rounded-full bg-muted"><CircleAlert size={20} className="text-muted-foreground" /></div><p className="font-medium">Your opportunity feed is clear</p><p className="mt-1 max-w-sm text-sm text-muted-foreground">Onboard an organization to start building a trustworthy Digital Twin and finding measurable opportunities.</p></div></div><div className="rounded-xl border border-border bg-surface"><div className="border-b border-border px-6 py-5"><h3 className="font-semibold">Decision timeline</h3><p className="mt-1 text-sm text-muted-foreground">Signals, decisions, approvals, and outcomes.</p></div><div className="flex min-h-64 flex-col items-center justify-center px-6 text-center"><Clock3 size={21} className="mb-3 text-muted-foreground" /><p className="text-sm font-medium">No activity yet</p><p className="mt-1 text-sm text-muted-foreground">Important changes will appear here with their evidence and scope.</p></div></div></section>
  </div>;
}
