(() => {
  const m=window.marketWatchPreview, esc=m.esc, icon=m.icon, button=m.button;
  let project=null, section='summary', report=null;
  const names={summary:'Summary',competitors:'Competitors',opportunity:'Local opportunity',advice:'Draft advice',sources:'Sources'};
  const icons={summary:'file-text',competitors:'store',opportunity:'map-pinned',advice:'list-checks',sources:'book-open'};
  const reports=new Map(), snapshots=new Map(), saved=new Set(), accepted=new Map();
  function getReport(p){
    if(reports.has(p.id))return reports.get(p.id);
    const event=p.kind==='event';
    const r={id:`report-${p.id}-${p.date}`,organization:'Example Kitchen',title:p.title,date:p.date,location:m.locations[p.location],brief:p.brief,version:p.state==='review'?p.version:Math.max(1,p.version-1),
      summary:event?'Make the event offer easy to understand, and check that the team can deliver it well. The useful opportunity is a clear family occasion, backed by reliable service.':p.kind==='feedback'?'Use customer feedback to identify a specific improvement. Look for repeated themes, then check them against your own service evidence before deciding what to change.':'Compare the value customers receive, the clarity of the offer and the service experience. Use those differences to choose what to investigate next.',
      findings:[{id:'offer-finding',kind:'insight',title:'Family offers appear in the local comparison',text:'The sampled public menu includes a family offer. Its visibility does not tell us how many customers buy it.',sources:['S1']},{id:'feedback-finding',kind:'insight',title:'Feedback includes praise and delivery concerns',text:'The illustrative review sample contains positive service comments and mentions of delays. It is not a representative customer survey.',sources:['S2']},{id:'period-finding',kind:'insight',title:p.location==='downtown'?'Your business evidence covers an earlier period':'Recent internal channel evidence is missing',text:p.location==='downtown'?'The available internal channel evidence is from August, while the external market observations are from September.':'There is no recent Marina channel report in the fixture, so this research cannot establish current internal performance.',sources:['S3']}],
      competitors:[{name:'Rival Kitchen',observation:'Family offer is easy to find in its public menu.',implication:'Compare the bundle contents and occasion, not just the headline price.',source:'S1'},{name:'Neighbour Table',observation:'Sample feedback mentions both friendly service and delivery delays.',implication:'Investigate service consistency as a possible point of difference.',source:'S2'}],
      opportunity:event?'A family-focused event offer could be worth exploring if the bundle is clear and the team has enough capacity. Start with the location’s existing customer occasion and service constraints.':'Look for an occasion or customer need that is poorly explained by the current offers. A clearer proposition may be more useful than a broad discount.',
      gap:p.location==='downtown'?'This research does not establish competitor sales or profit. Operating capacity is not confirmed, and the internal business evidence covers August.':'This research does not establish competitor sales or profit. Recent channel evidence and operating capacity are missing for Marina.',
      estimate:{label:'Rival Kitchen · Monthly sales scenario',range:'AED 45,000–70,000',note:'Speculative estimate, not reported revenue. These are assumed trading volumes, not measured competitor orders.',assumptions:'Scenario only: assume 40–60 orders per day, an average order value of AED 38 and 30 trading days. That gives AED 45,600–68,400, rounded to a broad range. The order volume is an analyst assumption; reviews and visible offers do not establish it. This is sales before costs, not profit.'},
      advice:[{id:'bundle',title:event?'Draft one clear family bundle':'Compare one offer against a specific customer need',why:'Use the public offer comparison to identify a clear occasion and explain what the customer receives.',next:'Confirm the items, availability and margin before making it a campaign proposal.',sources:['S1','S4'],label:'Offer planning'},{id:'capacity',title:'Confirm service capacity before promoting',why:'A promotion is only useful if the location can fulfil the extra demand reliably.',next:'Review preparation times, cancellation reasons and the team’s capacity for the chosen period.',sources:['S2','S3'],label:'Operations'},{id:'measure',title:'Choose a small, measurable trial',why:'A bounded trial can reveal whether the offer attracts useful demand without assuming a financial return.',next:'Define the period, comparison baseline and success measures before seeking campaign approval.',sources:['S3','S4'],label:'Measurement'}],
      sources:[{id:'S1',title:'Rival Kitchen · Public menu and offer page',meta:'External source · 11 Sep 2026',detail:'Illustrative source record for the competitor offer comparison. The production report links each supported statement to the retrieved page and passage.'},{id:'S2',title:'Neighbour Table · Public customer feedback',meta:'External source · 10 Sep 2026',detail:'Illustrative review sample. Positive and negative themes are presented as sampled feedback; they do not establish sales volumes.'},{id:'S3',title:'Example Kitchen · Channel evidence',meta:p.location==='downtown'?'Internal business evidence · Downtown · 1–31 Aug 2026':'Internal coverage gap · Marina · No recent reporting period',detail:p.location==='downtown'?'Illustrative business evidence about fulfilment. Its reporting period is separate from the research date.':'The fixture has no recent Marina channel report. This is a coverage gap, not evidence of business performance.'},{id:'S4',title:'Example Kitchen · Saved growth objective',meta:'Business Memory · Updated 10 Sep 2026',detail:'Illustrative saved objective and operating constraints. Private business context informs relevance; it is not sent as a public search query.'}]
    };reports.set(p.id,r);snapshots.set(r.id,{report:r,project:structuredClone(p)});return r;
  }
  const cite=ids=>ids.map(id=>`<button class="mw-citation" data-mwr-source="${id}" aria-label="See source ${id}">[${id}]</button>`).join('');
  function content(){
    const r=report;
    if(section==='summary')return `<div class="mw-eyebrow">THE SHORT VERSION</div><h3 style="margin-top:10px">What matters for ${esc(r.location)}</h3><p class="mw-report-lead">${esc(r.summary)}</p><div class="mw-report-question"><span>Your research question</span><p>${esc(r.brief)}</p></div><h4>Findings to keep in view</h4>${r.findings.map((f,i)=>`<div class="mw-finding"><span>0${i+1}</span><div><strong>${esc(f.title)}</strong><p>${esc(f.text)} ${cite(f.sources)}</p><label style="display:flex;align-items:center;gap:7px;font-size:10px;margin-top:9px;color:var(--muted-foreground)"><input type="checkbox" style="accent-color:var(--primary)" data-mwr-advice="${f.id}" ${(m.selectedAdvice.get(r.id)||new Set()).has(f.id)?'checked':''}>Select finding for Insights</label></div></div>`).join('')}<div class="mw-report-gap">${icon('info')}<div><strong>Where the evidence is incomplete</strong><p>${esc(r.gap)}</p></div></div>`;
    if(section==='competitors')return `<h3>Competitors & their offers</h3><p>Compare the offer and customer experience. Public visibility is a signal, not proof of business performance.</p><table class="mw-competitor-table"><thead><tr><th>Competitor</th><th>What we found</th><th>Why it matters</th></tr></thead><tbody>${r.competitors.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.observation)} ${cite([c.source])}</td><td>${esc(c.implication)}</td></tr>`).join('')}</tbody></table><div class="mw-estimate"><span class="mw-small-tag">Speculative estimate</span><h4>${esc(r.estimate.label)}</h4><div class="mw-estimate-number">${esc(r.estimate.range)} <span>/ month</span></div><p>${esc(r.estimate.note)}</p><details open><summary>Assumptions behind this range</summary><p>${esc(r.estimate.assumptions)}</p></details></div>`;
    if(section==='opportunity')return `<h3>The local opportunity</h3><p class="mw-report-lead">${esc(r.opportunity)} ${cite(['S1','S3','S4'])}</p><h4>What to check before committing</h4>${[{title:'Customer occasion',text:'Make the intended customer and the reason to buy explicit.'},{title:'Operating capacity',text:'Confirm available items, preparation limits and fulfilment coverage at this location.'},{title:'Commercial fit',text:'Check the proposed offer against costs and the organization’s goals before approving a campaign.'}].map((f,i)=>`<div class="mw-finding"><span>0${i+1}</span><div><strong>${f.title}</strong><p>${f.text}</p></div></div>`).join('')}<div class="mw-report-gap">${icon('circle-help')}<div><strong>Potential opportunity, not a promised result</strong><p>The report proposes what to investigate. It does not claim that a campaign has earned revenue or profit.</p></div></div>`;
    if(section==='advice'){const selected=m.selectedAdvice.get(r.id)||new Set();return `<h3>Draft advice for your review</h3><p>Choose the ideas worth taking forward. Each one keeps its link to this report and supporting evidence.</p>${r.advice.map(a=>`<article class="mw-advice-card"><label><input type="checkbox" data-mwr-advice="${a.id}" ${selected.has(a.id)?'checked':''}><span>${esc(a.title)}</span></label><p>${esc(a.why)} ${cite(a.sources)}</p><p><strong>Next step:</strong> ${esc(a.next)}</p><div class="mw-advice-meta"><span>${a.label}</span><span>Review required</span></div></article>`).join('')}<div class="mw-report-gap">${icon('shield-check')}<div><strong>Your review comes first</strong><p>These are draft ideas. Campaign approval, budget and publishing remain separate decisions.</p></div></div>${saved.has(r.id)?'<p class="mw-review-saved" style="margin-top:17px">'+icon('check')+' Your selection is saved for later in this preview.</p>':''}`;}
    return `<h3>Sources & evidence</h3><p>Report date: ${r.date}. Evidence periods and source dates are shown separately below.</p>${r.sources.map(s=>`<article class="mw-source" id="mw-source-${s.id}"><h4>[${s.id}] ${esc(s.title)}</h4><p>${esc(s.meta)}</p><p>${esc(s.detail)}</p></article>`).join('')}<div class="mw-report-gap">${icon('info')}<div><strong>Design preview · Fictional source records</strong><p>This report demonstrates reading and review. These examples are not a completed live research run.</p></div></div>`;
  }
  function render(){
    m.body.innerHTML=`<div class="mw-reader"><nav class="mw-report-nav" aria-label="Report sections"><p>IN THIS REPORT</p>${Object.keys(names).map(key=>`<button data-mwr-section="${key}" ${section===key?'aria-current="page"':''}>${icon(icons[key])}${names[key]}</button>`).join('')}<p class="mw-report-note">Brief ${report.version}<br>Report · ${report.date}<br>${esc(report.location)}</p></nav><section class="mw-report-content" id="mw-report-content" aria-label="${names[section]}">${content()}</section></div>`;
    requestAnimationFrame(()=>m.revealHorizontal(m.body.querySelector('[data-mwr-section][aria-current="page"]')));
    const selected=m.selectedAdvice.get(report.id)||new Set();
    m.footer.innerHTML=`<span class="mw-footer-note">${icon('file-check-2')} Fictional report · ${report.date}</span><div class="mw-actions">${button(icon('download')+' Download PDF','download-report')}${button(section==='advice'?'Save selection for later':'Save for later','save-review')}${section==='advice'?button('Review selection'+(selected.size?` (${selected.size})`:''),'review-selection',selected.size?'':'disabled',true):button('Review draft advice '+icon('arrow-right'),'review-advice','',true)}</div>`;
  }
  function open(p){project=p;report=getReport(p);section='summary';m.openModal('report');m.popup.classList.add('mw-report-dialog');m.header(report.title,`${report.location} · Report ${report.date} · Brief ${report.version}`,'RESEARCH REPORT');render();}
  function openExact(id){const snap=snapshots.get(id);if(!snap)return;project=snap.project;report=snap.report;section='summary';m.openModal('report');m.popup.classList.add('mw-report-dialog');m.header(report.title,`${report.location} · Report ${report.date} · Brief ${report.version}`,'RESEARCH REPORT');render();}
  const originalCard=recCard;
  recCard=function(item,prefix){let html=originalCard(item,prefix);if(!item.marketReports)return html;return html.replace(' · generated 3 Mar','').replace('</article>',`<div class="mt-4 flex flex-wrap gap-3 text-xs sm:ml-11">${item.marketReports.map(id=>`<button class="link" data-mwr-report="${esc(id)}">${icon('file-text')} Read source report · ${esc(snapshots.get(id).report.date)}</button>`).join('')}</div></article>`);};
  function selectedItems(){const ids=m.selectedAdvice.get(report.id)||new Set();return [...report.advice.map(a=>({...a,kind:'recommendation'})),...report.findings].filter(a=>ids.has(a.id));}
  function acceptSelection(){
    let createdRecommendations=0,createdInsights=0,existing=0;
    for(const item of selectedItems()){
      const key=[project.location,item.kind,item.title,item.next||item.text].map(s=>s.normalize('NFKC').toLowerCase().replace(/\s+/g,' ').trim()).join('|');
      let record=accepted.get(key);
      if(record){if(!record.reports.includes(report.id))record.reports.push(report.id);existing++;continue;}
      record={id:'reviewed-'+crypto.randomUUID(),kind:item.kind,title:item.title,text:item.text||item.why,location:project.location,reports:[report.id]};accepted.set(key,record);
      if(item.kind==='recommendation'){recommendations.unshift({id:record.id,title:esc(item.title),detail:esc(item.why+' Next step: '+item.next),scope:esc(report.location),evidence:esc('Market Watch · '+report.date),tag:esc(item.label),state:null,feedback:null,marketReports:record.reports});createdRecommendations++;}
      else createdInsights++;
    }
    renderAdvice();renderReviewedInsights();const live=m.projects.find(p=>p.id===project.id);if(live)live.reviewed=true;m.renderProjects();m.setView('accepted');m.popup.classList.remove('mw-report-dialog');m.header('Selected items added',`${report.title} · ${report.date}`,'REVIEW SAVED');m.body.innerHTML=`<div class="mw-form-tip">${icon('check-check')}<div><strong>${createdRecommendations} ${createdRecommendations===1?'recommendation':'recommendations'} · ${createdInsights} ${createdInsights===1?'insight':'insights'} added</strong><p>${existing?`${existing} previously accepted ${existing===1?'item was':'items were'} kept without creating duplicates. `:''}Each item links back to this report. Campaign execution still follows its own approval.</p></div></div>`;m.footer.innerHTML=`${button('Back to report','back-to-report')}<div class="mw-actions">${createdInsights?button('View Insights','view-insights'):''}${button('View Recommendations','view-recommendations','',true)}</div>`;toast('Review saved in this preview. Selected items were added to the appropriate feeds.');
  }
  function renderReviewedInsights(){
    let host=document.getElementById('mw-reviewed-insights');if(!host){host=document.createElement('div');host.id='mw-reviewed-insights';document.querySelector('.mw-business .mw-minor-heading').after(host);}
    host.innerHTML=[...accepted.values()].filter(i=>i.kind==='insight').map(i=>`<article class="mw-insight" data-reviewed-insight="${i.id}"><div class="mw-square">${icon('file-check-2')}</div><div><h3>${esc(i.title)}</h3><p>${esc(i.text)}</p><div class="mw-evidence-line">${m.locations[i.location]} · Accepted from Market Watch</div>${i.reports.map(id=>`<button class="link" data-mwr-report="${esc(id)}">Read source report · ${esc(snapshots.get(id).report.date)} ${icon('arrow-up-right')}</button>`).join(' ')}</div></article>`).join('');
  }
  function pdfLines(r){return [
    ['title',r.title],['meta',`${r.organization} | ${r.location} | Report ${r.date} | Brief ${r.version}`],['meta','Design preview - Fictional report and source examples'],
    ['heading','The short version'],['text',r.summary],['heading','Research question'],['text',r.brief],
    ...r.findings.flatMap(f=>[['heading',f.title],['text',f.text+' '+f.sources.map(id=>'['+id+']').join(' ')]]),
    ['heading','Evidence gaps'],['text',r.gap],['heading','Competitors and their offers'],
    ...r.competitors.flatMap(c=>[['heading',c.name],['text',c.observation+' ['+c.source+']'],['text',c.implication]]),
    ['heading','Speculative estimate'],['text',r.estimate.label+': '+r.estimate.range+' per month'],['text',r.estimate.note],['text',r.estimate.assumptions],
    ['heading','The local opportunity'],['text',r.opportunity],['heading','What to check before committing'],['text','Customer occasion: Make the intended customer and the reason to buy explicit.'],['text','Operating capacity: Confirm available items, preparation limits and fulfilment coverage at this location.'],['text','Commercial fit: Check the proposed offer against costs and the organization’s goals before approving a campaign.'],['text','Potential opportunity, not a promised result. The report proposes what to investigate; it does not claim that a campaign has earned revenue or profit.'],['heading','Draft advice for review'],
    ...r.advice.flatMap(a=>[['heading',a.title],['text',a.why+' '+a.sources.map(id=>'['+id+']').join(' ')],['text','Next step: '+a.next]]),
    ['heading','Sources and evidence'],...r.sources.flatMap(s=>[['heading','['+s.id+'] '+s.title],['meta',s.meta],['text',s.detail]])
  ];}
  function makePdf(r){
    // A deterministic English-fixture PDF export, built from the exact reader data.
    const ascii=s=>String(s).normalize('NFKD').replace(/[\u2010-\u2015]/g,'-').replace(/[\u2018\u2019]/g,"'").replace(/[\u201c\u201d]/g,'"').replace(/\u00b7/g,'|').replace(/[^\x20-\x7e]/g,'');
    const pdfEscape=s=>ascii(s).replace(/([\\()])/g,'\\$1');
    const pages=[];let commands=[],y=775;
    function page(){if(commands.length){commands.push(`BT /F1 9 Tf 0.4 0.4 0.4 rg 50 30 Td (${pdfEscape(r.title)} | ${pages.length+1}) Tj ET`);pages.push(commands.join('\n'));}commands=[];y=775;}
    for(const [kind,value] of pdfLines(r)){
      const size=kind==='title'?21:kind==='heading'?12:kind==='meta'?9:10.5;
      const max=kind==='title'?43:kind==='heading'?76:kind==='meta'?95:91;
      const words=ascii(value).split(/\s+/);let rows=[],line='';
      for(let word of words){while(word.length>max){if(line){rows.push(line);line='';}rows.push(word.slice(0,max));word=word.slice(max);}if((line+' '+word).trim().length>max){rows.push(line);line=word;}else line=(line+' '+word).trim();}if(line)rows.push(line);
      if(y-(rows.length*(size+5)+14)<55)page();
      if(kind==='heading')y-=8;
      const color=kind==='heading'?'0.05 0.4 0.28':kind==='meta'?'0.43 0.43 0.43':'0.1 0.1 0.1';
      for(const row of rows){if(y<55)page();commands.push(`BT /${kind==='title'||kind==='heading'?'F2':'F1'} ${size} Tf ${color} rg 50 ${y.toFixed(1)} Td (${pdfEscape(row)}) Tj ET`);y-=size+5;}y-=8;
    }page();
    const objs=['<< /Type /Catalog /Pages 2 0 R >>','', '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>'];
    const kids=[];pages.forEach(stream=>{const pageId=objs.length+1,streamId=pageId+1;kids.push(`${pageId} 0 R`);objs.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${streamId} 0 R >>`);objs.push(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);});
    objs[1]=`<< /Type /Pages /Kids [${kids.join(' ')}] /Count ${pages.length} >>`;
    let pdf='%PDF-1.4\n',offsets=[0];objs.forEach((obj,i)=>{offsets.push(pdf.length);pdf+=`${i+1} 0 obj\n${obj}\nendobj\n`;});const xref=pdf.length;pdf+=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`;offsets.slice(1).forEach(offset=>pdf+=String(offset).padStart(10,'0')+' 00000 n \n');pdf+=`trailer\n<< /Size ${objs.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
    return pdf;
  }
  document.addEventListener('click',e=>{
    const b=e.target.closest('[data-mwr-section],[data-mwr-source],[data-mwr-report],[data-mw-action]');if(!b)return;
    if(b.dataset.mwrReport){openExact(b.dataset.mwrReport);return;}if(!report)return;
    if(b.dataset.mwrSection){section=b.dataset.mwrSection;render();m.body.querySelector('[data-mwr-section][aria-current="page"]').focus({preventScroll:true});}
    if(b.dataset.mwrSource){section='sources';render();const source=document.getElementById('mw-source-'+b.dataset.mwrSource);source.classList.add('flash');source.scrollIntoView({block:'nearest'});}
    if(b.dataset.mwAction==='review-advice'){section='advice';render();}
    if(b.dataset.mwAction==='save-review'){saved.add(report.id);toast('Report and selected advice saved for later in this preview.');render();}
    if(b.dataset.mwAction==='review-selection'){
      const chosen=selectedItems();m.setView('selection');m.popup.classList.remove('mw-report-dialog');m.header('Review selected items',`${report.title} · ${report.date}`,'REPORT REVIEW');m.body.innerHTML=chosen.map(a=>`<div class="mw-history-row"><div><strong>${esc(a.title)}</strong><p>${esc(a.next||a.text)}</p><p style="color:var(--primary)">${icon(a.kind==='recommendation'?'lightbulb':'file-text')} ${a.kind==='recommendation'?'Adds to Recommendations':'Adds to Insights'}</p></div>${icon('check')}</div>`).join('')+`<p class="mw-detail-intro" style="margin-top:20px">The platform chooses the destination from each item’s type. Only these selected items will be added, with their report and source links.</p>`;m.footer.innerHTML=`${button('Back to report','back-to-report')}${button('Accept selected items','accept-selection','',true)}`;
    }
    if(b.dataset.mwAction==='back-to-report'){m.setView('report');m.popup.classList.add('mw-report-dialog');m.header(report.title,`${report.location} · Report ${report.date} · Brief ${report.version}`,'RESEARCH REPORT');section='advice';render();}
    if(b.dataset.mwAction==='save-selection'){saved.add(report.id);toast('Selection saved for later in this preview.');m.closeModal();}
    if(b.dataset.mwAction==='accept-selection')acceptSelection();
    if(b.dataset.mwAction==='view-recommendations'){m.closeModal();tab('recommendations');}
    if(b.dataset.mwAction==='view-insights'){m.closeModal();tab('insights');document.querySelector('.mw-business').scrollIntoView({block:'start'});}
    if(b.dataset.mwAction==='download-report'){
      const url=URL.createObjectURL(new Blob([makePdf(report)],{type:'application/pdf'}));const a=document.createElement('a');a.id='download-research-report-'+Date.now();a.href=url;a.download=report.title.replace(/[^a-z0-9]+/gi,'-').replace(/-$/,'')+'.pdf';a.hidden=true;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('PDF downloaded from the same report content.');
    }
  });
  document.addEventListener('change',e=>{if(!e.target.dataset.mwrAdvice)return;const selected=m.selectedAdvice.get(report.id)||new Set();e.target.checked?selected.add(e.target.dataset.mwrAdvice):selected.delete(e.target.dataset.mwrAdvice);m.selectedAdvice.set(report.id,selected);const b=m.footer.querySelector('[data-mw-action="review-selection"]');if(b){b.disabled=selected.size===0;b.textContent='Review selection'+(selected.size?` (${selected.size})`:'');}});
  window.marketWatchReport={open,getReport,makePdf,pdfLines,accepted};
})();
