const {chromium}=require('@playwright/test');
const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs');
(async()=>{
  const browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1100},acceptDownloads:true});
  const errors=[],checks=[];
  page.on('pageerror',e=>errors.push(e.message));
  const check=(name,value)=>{assert.ok(value,name);checks.push(name);};
  const button=name=>page.getByRole('button',{name,exact:true});
  const screenshot=name=>page.screenshot({path:path.join(__dirname,name)});
  const boot=async()=>{await page.goto('file://'+path.join(__dirname,'prototype.html'),{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.marketWatchPreview&&window.marketWatchReport&&document.querySelector('#tab-insights').getAttribute('aria-selected')==='true');await page.evaluate(()=>document.fonts.ready);};
  await boot();
  check('Starts on Insights & market',await page.locator('#panel-insights').isVisible());
  check('Five independent project examples',await page.locator('[data-project-id]').count()===5);
  check('No desktop overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await screenshot('01-market-watch-desktop.png');
  await page.getByLabel('Research location',{exact:true}).selectOption('marina');
  check('Location filter affects the featured report and project list',await page.locator('[data-project-id]').count()===2&&await page.locator('.mw-feature').count()===0);
  await page.getByLabel('Find a research project',{exact:true}).fill('no matching project');
  check('Search has a useful empty state',await page.getByRole('heading',{name:'No projects match these filters'}).isVisible());
  await button('Clear filters').click();
  check('Clearing filters restores projects',await page.locator('[data-project-id]').count()===5);
  await button('New research').click();await screenshot('02-new-research-desktop.png');
  await button('Continue').click();
  check('Missing brief is explained inline',await page.locator('#mw-form-error').isVisible());
  await page.getByLabel('What would you like to achieve?',{exact:true}).fill('Prepare an event offer without overwhelming our delivery team.');
  await page.getByLabel('Project name Optional',{exact:true}).fill('Event opportunity <test>');
  await page.getByLabel('Event or target date Optional',{exact:true}).fill('2026-12-02');
  await button('Continue').click();await button('Continue').click();
  check('Location must be chosen explicitly',await page.locator('#mw-form-error').innerText()==='Choose the business location this research should help.');
  await page.getByLabel('Business location',{exact:true}).selectOption('downtown');
  await button('Add a competitor').click();
  await page.getByLabel('Competitor name',{exact:true}).fill('Rival <test> கடை');
  await page.getByLabel('Website Optional',{exact:true}).fill('javascript:alert(1)');
  await button('Save competitor').click();
  check('Unsafe website scheme is rejected',await page.locator('#mw-competitor-error').isVisible());
  await page.getByLabel('Website Optional',{exact:true}).fill('https://example.com');
  await page.getByLabel('Location hint Optional',{exact:true}).fill('Downtown');
  await button('Save competitor').click();
  check('Non-Latin competitor name is preserved as text',(await page.locator('#mw-competitors').innerText()).includes('Rival <test> கடை'));
  check('Competitor text cannot create markup',await page.locator('#mw-competitors test').count()===0);
  await screenshot('03-research-scope-desktop.png');
  await button('Continue').click();await button('Start research').click();
  check('Research frequency requires a deliberate choice',(await page.locator('#mw-form-error').innerText()).includes('Choose one-time'));
  await page.getByRole('radio',{name:'Keep monitoring Receive fresh reports as the market changes.'}).check();
  await button('Start research').click();
  check('Recurring mode requires a cadence',(await page.locator('#mw-form-error').innerText()).includes('frequency and start time'));
  await page.getByLabel('Frequency',{exact:true}).selectOption('weekly');
  await page.getByLabel('Stop monitoring on Optional',{exact:true}).fill('2026-12-03');
  await screenshot('04-review-brief-desktop.png');
  check('Reviewed brief retains question and competitor',(await page.locator('.mw-review').innerText()).includes('Prepare an event offer')&&(await page.locator('.mw-review').innerText()).includes('Rival <test> கடை'));
  await page.getByRole('radio',{name:'One-time Answer this question once.'}).check();
  check('One-time mode hides schedule controls',await page.locator('#mw-cadence').count()===0);
  await button('Start research').click();
  check('Start creates a separate queued project',await page.evaluate(()=>marketWatchPreview.projects.length===6&&marketWatchPreview.projects[5].state==='queued'));
  check('New work leaves the existing competitor run active',await page.evaluate(()=>marketWatchPreview.projects.find(p=>p.id==='competitors').state==='researching'));
  check('Created title is rendered as literal text',(await page.locator('#mw-dialog-title').innerText())==='Event opportunity <test>');
  await screenshot('05-research-progress-desktop.png');
  await button('Close').click();
  check('Closing the dialog does not cancel research',await page.evaluate(()=>marketWatchPreview.projects[5].state==='queued'));
  await page.getByLabel('Research location',{exact:true}).selectOption('all');
  await page.getByRole('button',{name:'Open Competitor monitoring',exact:true}).click();
  await button('Pause monitoring').click();
  check('Pause affects the schedule while current research continues',await page.evaluate(()=>{const p=marketWatchPreview.projects.find(p=>p.id==='competitors');return p.schedulePaused&&p.state==='researching';}));
  check('Paused monitoring can be resumed',await button('Resume monitoring').isVisible());
  await button('Stop this research').click();
  check('Stop affects only that project',await page.evaluate(()=>marketWatchPreview.projects.find(p=>p.id==='competitors').state==='stopped'&&marketWatchPreview.projects[5].state==='queued'));
  await button('Close').click();
  await page.getByRole('button',{name:'Open Neighbourhood offers',exact:true}).click();
  await button('Retry update').click();
  check('Retry keeps the previous report available',await page.evaluate(()=>{const p=marketWatchPreview.projects.find(p=>p.id==='offers');return p.state==='queued'&&p.date==='6 Sep 2026';}));
  await button('Close').click();
  await button('Review report').click();await screenshot('06-report-summary-desktop.png');
  check('Readable report has exact project identity',(await page.locator('#mw-dialog-title').innerText())==='Prepare for National Day'&&(await page.locator('#mw-dialog-subtitle').innerText()).includes('12 Sep 2026'));
  check('Downtown report does not borrow Marina gaps',!(await page.locator('#mw-report-content').innerText()).includes('Marina'));
  await page.getByRole('button',{name:'See source S1',exact:true}).first().click();
  check('Citation opens its source record',await page.locator('#mw-source-S1').isVisible()&&await page.locator('#mw-source-S1').evaluate(e=>e.classList.contains('flash')));
  await button('Competitors').click();await screenshot('07-report-estimate-desktop.png');
  check('Speculative range keeps assumptions on the same surface',(await page.locator('.mw-estimate').innerText()).includes('Speculative estimate')&&(await page.locator('.mw-estimate').innerText()).includes('40–60 orders per day')&&(await page.locator('.mw-estimate').innerText()).includes('not profit'));
  const downloadPromise=page.waitForEvent('download');await button('Download PDF').click();const download=await downloadPromise;await download.saveAs(path.join(__dirname,'sample-research-report.pdf'));
  check('PDF is a real downloadable document',fs.readFileSync(path.join(__dirname,'sample-research-report.pdf')).subarray(0,8).toString()==='%PDF-1.4');
  await button('Summary').click();await page.locator('[data-mwr-advice="offer-finding"]').check();
  await button('Draft advice').click();await page.locator('[data-mwr-advice="bundle"]').check();await page.locator('[data-mwr-advice="capacity"]').check();await screenshot('08-draft-advice-desktop.png');
  await button('Review selection (3)').click();
  check('Review explains destinations by item type',(await page.locator('#mw-dialog-body').innerText()).includes('Adds to Recommendations')&&(await page.locator('#mw-dialog-body').innerText()).includes('Adds to Insights'));
  await screenshot('09-accept-items-desktop.png');
  await button('Accept selected items').click();
  check('Selected items enter their respective feeds',await page.evaluate(()=>[...marketWatchReport.accepted.values()].filter(x=>x.kind==='recommendation').length===2&&[...marketWatchReport.accepted.values()].filter(x=>x.kind==='insight').length===1));
  await button('View Recommendations').click();
  check('Recommendations retain their exact source report',await page.locator('#recommendation-list [data-mwr-report]').count()===2);
  await screenshot('10-recommendations-handoff-desktop.png');
  await page.locator('#recommendation-list [data-mwr-report]').first().click();
  check('Feed source link returns to the reviewed report',(await page.locator('#mw-dialog-title').innerText())==='Prepare for National Day');
  await button('Draft advice').click();await button('Review selection (3)').click();await button('Accept selected items').click();
  check('Repeated acceptance does not duplicate items',await page.evaluate(()=>marketWatchReport.accepted.size===3));
  check('Repeated acceptance is explained',(await page.locator('#mw-dialog-body').innerText()).includes('3 previously accepted items'));
  await button('Back to report').click();await page.keyboard.press('Escape');
  await page.getByRole('tab',{name:'Insights & market',exact:true}).click();
  check('Informational item is in Business insights',await page.locator('[data-reviewed-insight]').count()===1);
  await button('New research').click();await page.getByLabel('What would you like to achieve?',{exact:true}).fill('Keep this unfinished question');await page.keyboard.press('Escape');
  check('Escape protects an unsaved brief',await button('Keep editing').isVisible());await button('Keep editing').click();
  check('Keep editing retains input',(await page.getByLabel('What would you like to achieve?',{exact:true}).inputValue())==='Keep this unfinished question');
  await page.keyboard.press('Escape');await button('Discard draft').click();
  check('Discard restores focus to the opening control',await button('New research').evaluate(e=>document.activeElement===e));
  await page.setViewportSize({width:390,height:844});await boot();await screenshot('11-market-watch-mobile.png');
  check('No phone page overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await button('New research').click();await screenshot('12-new-research-mobile.png');
  check('Phone dialog and footer fit the viewport',await page.locator('#mw-dialog').evaluate(e=>e.getBoundingClientRect().width<=innerWidth)&&await page.locator('#mw-dialog-footer').evaluate(e=>e.getBoundingClientRect().bottom<=innerHeight));
  await page.keyboard.press('Escape');await button('Review report').click();await screenshot('13-report-mobile.png');
  check('Phone reader reflows within the viewport',await page.locator('#mw-report-content').evaluate(e=>e.scrollWidth<=e.clientWidth));
  await button('Competitors').click();check('Phone comparison and estimate do not overflow',await page.locator('#mw-report-content').evaluate(e=>e.scrollWidth<=e.clientWidth));
  await page.setViewportSize({width:320,height:740});check('Narrow phone report fits',await page.locator('#mw-report-content').evaluate(e=>e.scrollWidth<=e.clientWidth));
  await page.keyboard.press('Escape');check('Narrow phone page fits',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  check('No JavaScript errors',errors.length===0);
  fs.writeFileSync(path.join(__dirname,'verification.json'),JSON.stringify({checkedAt:new Date().toISOString(),scope:'Fictional standalone prototype; no live research or application integration',checks,errors},null,2)+'\n');
  console.log(JSON.stringify({passed:checks.length,errors}));
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
