(() => {
  const q = (s) => document.querySelector(s);
  const esc = (s = '') => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const icon = (s) => `<iconify-icon icon="lucide:${s}"></iconify-icon>`;
  const locations = {downtown:'Downtown',marina:'Marina'};
  const projects = [
    {id:'event',title:'Prepare for National Day',location:'downtown',mode:'once',state:'review',date:'12 Sep 2026',brief:'Understand nearby offers and customer expectations so we can plan a useful National Day promotion.',takeaway:'Compare family offers and check delivery capacity before choosing a promotion.',kind:'event',version:1},
    {id:'competitors',title:'Competitor monitoring',location:'downtown',mode:'recurring',state:'researching',date:'11 Sep 2026',brief:'Follow changes in nearby competitors, their offers and customer feedback.',kind:'competitors',version:4},
    {id:'weekend',title:'Weekend delivery opportunity',location:'marina',mode:'once',state:'queued',date:null,brief:'Find opportunities to improve weekend delivery demand around Marina.',kind:'delivery',version:1},
    {id:'feedback',title:'Local customer feedback',location:'downtown',mode:'recurring',state:'paused',date:'8 Sep 2026',brief:'Understand what local customers like and what they want to improve.',kind:'feedback',version:3},
    {id:'offers',title:'Neighbourhood offers',location:'marina',mode:'recurring',state:'failed',date:'6 Sep 2026',brief:'Compare current nearby offers without assuming that a lower price means better value.',kind:'offers',version:2}
  ];
  let filter='all', draft=null, step=1, view='new', current=null, editor=null, opener=null, selectedAdvice=new Map();
  const popup=q('#mw-dialog'), body=q('#mw-dialog-body'), footer=q('#mw-dialog-footer');
  const stateLabels={review:'Ready to review',researching:'Researching',queued:'Queued',paused:'Monitoring paused',failed:'Update needs attention',stopped:'Research stopped'};
  const stateIcons={review:'check',researching:'loader-circle',queued:'clock-3',paused:'pause',failed:'circle-alert',stopped:'circle-stop'};
  const button=(text,action,extra='',primary=false)=>`<button class="btn ${primary?'btn-primary':''}" data-mw-action="${action}" ${extra}>${text}</button>`;
  const modeLabel=p=>p.mode==='once'?'One-time research':'Recurring research';
  const badge=p=>`<span class="mw-badge ${p.state==='review'?'ready':p.state==='failed'?'attention':''}">${icon(stateIcons[p.state])}${p.reviewed?'Reviewed':stateLabels[p.state]}</span>${p.schedulePaused?`<span class="mw-badge">${icon('pause')}Monitoring paused</span>`:''}`;
  const matchesState=(p,f)=>f==='all'||f==='review'&&p.state==='review'&&!p.reviewed||f==='running'&&['researching','queued'].includes(p.state)||f==='paused'&&(p.state==='paused'||p.schedulePaused)||f==='attention'&&p.state==='failed';
  const filtered=()=>projects.filter(p=>(q('#mw-location').value==='all'||p.location===q('#mw-location').value)&&p.title.toLowerCase().includes(q('#mw-search').value.trim().toLowerCase()));
  const freshDraft=()=>({title:'',brief:'',eventDate:'',location:q('#mw-location').value==='all'?'':q('#mw-location').value,area:'',competitors:[],mode:'',cadence:'',time:'09:00',endDate:'',dirty:false});

  function renderProjects(){
    const candidates=filtered(), visible=candidates.filter(p=>matchesState(p,filter));
    document.querySelectorAll('[data-mw-filter]').forEach(b=>{b.setAttribute('aria-pressed',String(filter===b.dataset.mwFilter));b.querySelector('span').textContent=candidates.filter(p=>matchesState(p,b.dataset.mwFilter)).length;});
    const featured=visible.find(p=>p.state==='review'&&!p.reviewed)||visible.find(p=>p.state==='review');
    let html=featured?`<article class="mw-feature" data-project-id="${featured.id}"><div class="mw-feature-main"><div class="mw-feature-story"><div class="mw-feature-top">${badge(featured)}<span class="mw-meta">Report · ${featured.date}</span></div><h3>${esc(featured.title)}</h3><div class="mw-meta">${icon('map-pin')} ${locations[featured.location]} <span aria-hidden="true"> · </span> ${modeLabel(featured)}</div><p class="mw-takeaway">${esc(featured.takeaway)}</p></div><aside class="mw-feature-side"><h4>In this report</h4><ul><li>${icon('store')} Competitors & their offers</li><li>${icon('messages-square')} What customers are saying</li><li>${icon('map-pinned')} The local opportunity</li><li>${icon('list-checks')} Draft advice for your review</li></ul></aside></div><div class="mw-feature-footer"><div class="mw-actions">${button((featured.reviewed?'Read report ':'Review report ')+icon('arrow-up-right'),'report',`data-mw-id="${featured.id}"`,true)}${button('Project history','history',`data-mw-id="${featured.id}"`)}</div><span>Based on brief ${featured.version} · ${featured.reviewed?'Review saved':'Advice awaits your review'}</span></div></article>`:'';
    const rows=visible.filter(p=>p!==featured);
    if(rows.length)html+=`<div class="mw-project-list">${rows.map(p=>`<article class="mw-project-row" data-project-id="${p.id}"><div class="mw-square ${p.state==='paused'?'neutral':''}">${icon(p.mode==='once'?'file-search':'radar')}</div><div><h3>${esc(p.title)}</h3><p>${locations[p.location]} · ${modeLabel(p)}</p></div><div class="mw-project-status">${badge(p)}${p.state==='researching'?`<span>Comparing public sources</span>`:p.state==='queued'?`<span>Waiting for research to start</span>`:p.date?`<button class="link" data-mw-action="report" data-mw-id="${p.id}">Previous report · ${p.date}</button>`:`<span>No completed report yet</span>`}</div><button class="mw-icon-button" aria-label="Open ${esc(p.title)}" data-mw-action="project" data-mw-id="${p.id}">${icon('arrow-right')}</button></article>`).join('')}</div>`;
    if(!visible.length)html=`<div class="mw-empty">${icon('search')}<h3>No projects match these filters</h3><p>Try another location, status or search term.</p>${button('Clear filters','clear')}</div>`;
    html+=`<div class="mw-list-foot"><span>${visible.length} ${visible.length===1?'project':'projects'} shown</span><span>Past reports stay available when research updates.</span></div>`;
    q('#mw-projects').innerHTML=html;
  }
  function header(title,subtitle,kicker='MARKET WATCH'){
    q('#mw-dialog-title').textContent=title;q('#mw-dialog-subtitle').textContent=subtitle;q('#mw-dialog-kicker').textContent=kicker;
  }
  function openModal(next){
    if(!popup.open)opener=document.activeElement;view=next;popup.classList.remove('mw-report-dialog');q('#mw-steps').hidden=next!=='new';
    if(!popup.open)popup.showModal();body.scrollTop=0;
  }
  function closeModal(){popup.close();if(opener?.isConnected)opener.focus();}
  function newResearch(){draft=freshDraft();step=1;editor=null;openModal('new');renderWizard();}
  function renderSteps(){q('#mw-steps').innerHTML=['Brief','Scope','Review'].map((name,i)=>`${i?'<div class="mw-step-line"></div>':''}<button class="mw-step ${step>i+1?'complete':''}" ${step===i+1?'aria-current="step"':''} ${i+1>step?'disabled':''} data-mw-action="step" data-step="${i+1}"><span>${step>i+1?icon('check'):i+1}</span>${name}</button>`).join('');}
  const field=(key,label,type='text',placeholder='',hint='')=>`<div class="mw-field"><label for="mw-${key}">${label}</label><input id="mw-${key}" data-mw-field="${key}" type="${type}" value="${esc(draft[key])}" placeholder="${esc(placeholder)}">${hint?`<small>${hint}</small>`:''}</div>`;
  function renderWizard(){
    view='new';q('#mw-steps').hidden=false;renderSteps();
    header('New research',step===1?'A useful answer starts with a clear question.':step===2?'Choose the local market and context to investigate.':'Check the brief before research starts.');
    if(step===1)body.innerHTML=`<p id="mw-form-error" class="mw-error" role="alert" hidden></p><div class="mw-field"><label for="mw-brief">What would you like to achieve?</label><textarea id="mw-brief" data-mw-field="brief" placeholder="For example: Find out what nearby competitors are doing for National Day and how we could attract more family orders.">${esc(draft.brief)}</textarea><small>Tell us the business question, occasion or opportunity you want to explore.</small></div><div class="mw-two-fields">${field('title','Project name <span>Optional</span>','text','A short name you’ll recognise')}${field('eventDate','Event or target date <span>Optional</span>','date')}</div><div class="mw-form-tip">${icon('sparkles')}<div><strong>From a question to a useful report</strong><p>We’ll research your market, connect it with your business context and prepare draft advice for you to review.</p><button class="link" style="font-size:11px;margin-top:9px" data-mw-action="example">Try an event brief ${icon('arrow-right')}</button></div></div>`;
    if(step===2)body.innerHTML=`<p id="mw-form-error" class="mw-error" role="alert" hidden></p><div class="mw-two-fields"><div class="mw-field"><label for="mw-location-input">Business location</label><select id="mw-location-input" data-mw-field="location"><option value="">Choose a location</option>${Object.entries(locations).map(([key,name])=>`<option value="${key}" ${draft.location===key?'selected':''}>${name}</option>`).join('')}</select><small>The outlet this research should help.</small></div>${field('area','Research area','text','Neighbourhood, city or service area','Use the area your customers and competitors serve.')}</div><div class="mw-subhead"><h3>Competitors to investigate</h3><span>Optional · Add the ones you know</span></div><div id="mw-competitors" class="mw-comp-list">${competitorRows()}</div><div id="mw-competitor-editor"></div><button class="btn" data-mw-action="add-competitor" style="font-size:11px">${icon('plus')} Add a competitor</button><div style="margin-top:23px"><div class="mw-subhead"><h3>What we’ll look into</h3></div><div class="mw-coverage"><span>Digital presence</span><span>Offers & pricing</span><span>Customer feedback</span><span>Local demand</span><span>Performance signals</span></div></div><details class="mw-context-details"><summary>Business context used for this research</summary><dl><dt>Business facts</dt><dd>Chosen location, service area and operating constraints</dd><dt>Channel evidence</dt><dd>${draft.location==='marina'?'Recent channel reports are missing.':'Downtown · 1–31 Aug 2026 · Delivery and direct orders'}</dd><dt>Business Memory</dt><dd>Saved growth objective and relevant customer feedback</dd></dl></details>`;
    if(step===3)body.innerHTML=`<p id="mw-form-error" class="mw-error" role="alert" hidden></p><fieldset class="mw-field"><legend>How often should we research this?</legend><div class="mw-frequency"><label><input type="radio" name="mw-frequency" value="once" data-mw-field="mode" ${draft.mode==='once'?'checked':''}><span><strong>One-time</strong><small>Answer this question once.</small></span></label><label><input type="radio" name="mw-frequency" value="recurring" data-mw-field="mode" ${draft.mode==='recurring'?'checked':''}><span><strong>Keep monitoring</strong><small>Receive fresh reports as the market changes.</small></span></label></div></fieldset><div id="mw-schedule">${scheduleFields()}</div><div class="mw-review"><div class="mw-review-title"><span>Your research brief</span><button class="link" data-mw-action="step" data-step="1">Edit brief</button></div><dl><dt>Question</dt><dd>${esc(draft.brief)}</dd><dt>Location</dt><dd>${locations[draft.location]}${draft.area?' · '+esc(draft.area):''} <button class="link" data-mw-action="step" data-step="2">Edit scope</button></dd>${draft.eventDate?`<dt>Target date</dt><dd>${esc(draft.eventDate)}</dd>`:''}<dt>Competitors</dt><dd>${draft.competitors.length?draft.competitors.map(c=>esc(c.name)).join(', '):'Find relevant competitors in the research area'}</dd><dt>Coverage</dt><dd>Presence, offers, feedback, local demand and performance signals</dd><dt>Business context</dt><dd>${draft.location==='downtown'?'August 2026 channel evidence; saved business facts and goals':'Saved business facts and goals; recent channel evidence is missing'}</dd></dl></div><div class="mw-outcome-note">${icon('file-check-2')}<div>You’ll receive a report and draft advice to review.<br><span style="color:var(--muted-foreground)">This creates a separate project. Existing research keeps its own schedule and history.</span></div></div>`;
    footer.innerHTML=`<span class="mw-footer-note">${icon('lock-keyhole')} Your business context stays private.</span><div class="mw-actions">${button(step===1?'Cancel':'Back',step===1?'close':'back')}${button(step===3?'Start research '+icon('arrow-right'):'Continue '+icon('arrow-right'),step===3?'start':'next','',true)}</div>`;
    body.scrollTop=0;
  }
  function competitorRows(){return draft.competitors.map((c,i)=>`<div class="mw-comp-row"><div class="mw-square">${icon('store')}</div><div><strong>${esc(c.name)}</strong><p>${esc(c.hint||'Location to be checked')}${c.website?' · '+esc(c.website):''}</p></div><button class="mw-icon-button" aria-label="Edit ${esc(c.name)}" data-mw-action="edit-competitor" data-index="${i}">${icon('pencil')}</button><button class="mw-icon-button" aria-label="Remove ${esc(c.name)}" data-mw-action="remove-competitor" data-index="${i}">${icon('x')}</button></div>`).join('');}
  function competitorEditor(index=null){editor=index;const c=index===null?{name:'',website:'',hint:''}:draft.competitors[index];q('#mw-competitor-editor').innerHTML=`<div class="mw-comp-editor"><p id="mw-competitor-error" class="mw-error" role="alert" hidden></p><div class="mw-field"><label for="mw-competitor-name">Competitor name</label><input id="mw-competitor-name" value="${esc(c.name)}" placeholder="Business name"></div><div class="mw-two-fields"><div class="mw-field"><label for="mw-competitor-website">Website <span>Optional</span></label><input id="mw-competitor-website" type="url" value="${esc(c.website)}" placeholder="https://example.com"></div><div class="mw-field"><label for="mw-competitor-hint">Location hint <span>Optional</span></label><input id="mw-competitor-hint" value="${esc(c.hint)}" placeholder="Neighbourhood or nearby landmark"></div></div><div class="mw-actions">${button('Save competitor','save-competitor','',true)}${button('Cancel','cancel-competitor')}</div></div>`;q('#mw-competitor-name').focus();}
  function scheduleFields(){return draft.mode==='recurring'?`<div class="mw-schedule"><div class="mw-two-fields"><div class="mw-field"><label for="mw-cadence">Frequency</label><select id="mw-cadence" data-mw-field="cadence"><option value="">Choose frequency</option><option value="weekly" ${draft.cadence==='weekly'?'selected':''}>Weekly</option><option value="daily" ${draft.cadence==='daily'?'selected':''}>Daily</option></select></div>${field('time','Research start time','time','','Location timezone · Asia/Dubai')}</div>${field('endDate','Stop monitoring on <span>Optional</span>','date','', 'Leave empty to continue until you pause monitoring.')}</div>`:'';}
  function error(message,id){const el=q('#mw-form-error');el.hidden=false;el.textContent=message;if(id){q(id).setAttribute('aria-invalid','true');q(id).focus();}else el.scrollIntoView({block:'nearest'});}
  function validStep(){if(step===1&&!draft.brief.trim()){error('Describe the question you want this research to answer.','#mw-brief');return false;}if(step===2&&!draft.location){error('Choose the business location this research should help.','#mw-location-input');return false;}if(step===2&&q('#mw-competitor-name')){error('Save or cancel the competitor you are editing before continuing.');return false;}return true;}
  function start(){
    if(!draft.mode){error('Choose one-time research or keep monitoring.');return;}
    if(draft.mode==='recurring'&&(!draft.cadence||!draft.time)){error('Choose a frequency and start time for monitoring.');return;}
    if(draft.mode==='recurring'&&draft.endDate&&draft.endDate<new Date().toISOString().slice(0,10)){error('Choose a future stop date or leave it empty.','#mw-endDate');return;}
    const p={id:crypto.randomUUID(),title:draft.title.trim()||draft.brief.trim().slice(0,90),location:draft.location,mode:draft.mode,state:'queued',date:null,brief:draft.brief.trim(),kind:'custom',version:1,settings:JSON.parse(JSON.stringify(draft))};
    projects.push(p);draft.dirty=false;filter='all';q('#mw-search').value='';q('#mw-location').value=p.location;renderProjects();current=p;showProject(p,true);
    toast('Preview project created. No live research was started.');
  }
  function showProject(p,justStarted=false){
    current=p;openModal('project');header(p.title,`${locations[p.location]} · ${modeLabel(p)}`);body.innerHTML=`${badge(p)}<p class="mw-detail-intro" style="margin-top:16px">${esc(p.brief)}</p>${['queued','researching'].includes(p.state)?`<ol class="mw-progress-list"><li><span class="mw-progress-dot current">${p.state==='researching'?icon('check'):'1'}</span><div><strong>${p.state==='queued'?'Research queued':'Brief saved'}</strong><p>${p.state==='queued'?'Your reviewed brief is saved. This project is waiting for research to start.':'The exact question and scope are saved for this update.'}</p></div></li><li><span class="mw-progress-dot ${p.state==='researching'?'current':''}">2</span><div><strong>Research the market</strong><p>Find and compare useful public evidence.</p></div></li><li><span class="mw-progress-dot">3</span><div><strong>Prepare your report</strong><p>Connect market findings with the business context.</p></div></li><li><span class="mw-progress-dot">4</span><div><strong>Ready for your review</strong><p>Read the report and consider the draft advice.</p></div></li></ol>`:`<div class="mw-form-tip" style="margin-top:22px">${icon(p.state==='failed'?'circle-alert':'archive')}<div><strong>${p.state==='failed'?'The last update did not finish':p.state==='paused'?'Future updates are paused':'This update has stopped'}</strong><p>${p.date?'Your previous report remains available.':'No report was completed for this attempt.'} Other projects at this location keep their own settings.</p></div></div>`}${justStarted?'<p class="mw-detail-intro" style="margin-top:18px">You can close this dialog and return to the project later.</p>':''}${p.date?`<div class="mw-history-row"><div><strong>Previous report · ${p.date}</strong><p>Based on an earlier brief revision</p></div>${button('Read report','report',`data-mw-id="${p.id}"`)}</div>`:''}`;
    footer.innerHTML=`<div class="mw-actions">${p.mode==='recurring'&&!p.schedulePaused&&p.state!=='paused'?button('Pause monitoring','pause'):p.state==='paused'||p.schedulePaused?button('Resume monitoring','resume'):''}${['researching','queued'].includes(p.state)?button('Stop this research','stop'):p.state==='failed'?button('Retry update','retry'):''}</div><div class="mw-actions">${button('History','history',`data-mw-id="${p.id}"`)}${button('Close','done','',true)}</div>`;
  }
  function history(p){current=p;openModal('history');header('Project history',`${p.title} · ${locations[p.location]}`);body.innerHTML=`<p class="mw-detail-intro">Each report keeps the question and evidence used for that update.</p><div class="mw-history-row"><div><strong>Current update</strong><p>Brief ${p.version} · ${stateLabels[p.state]}</p></div>${button('View update','project',`data-mw-id="${p.id}"`)}</div>${p.date?`<div class="mw-history-row"><div><strong>Report · ${p.date}</strong><p>Brief ${p.state==='review'?p.version:Math.max(1,p.version-1)} · Saved report</p></div>${button('Read report','report',`data-mw-id="${p.id}"`)}</div>`:'<p class="mw-detail-intro" style="margin-top:22px">No completed reports yet.</p>'}`;footer.innerHTML=button('Close','done');}
  function requestClose(){if(view==='new'&&draft?.dirty){view='discard';q('#mw-steps').hidden=true;header('Keep working on this brief?','Your unsaved changes are still here.');body.innerHTML='<p class="mw-detail-intro">Discarding this draft leaves all existing research projects unchanged.</p>';footer.innerHTML=`<span></span><div class="mw-actions">${button('Discard draft','discard')}${button('Keep editing','keep','',true)}</div>`;}else closeModal();}
  function simpleDetail(title,html){openModal('detail');header(title,'Business context');body.innerHTML=html;footer.innerHTML=button('Close','done');}

  document.addEventListener('input',e=>{const key=e.target.dataset.mwField;if(key&&draft){draft[key]=e.target.value;draft.dirty=true;e.target.removeAttribute('aria-invalid');}});
  document.addEventListener('change',e=>{const key=e.target.dataset.mwField;if(!key||!draft)return;draft[key]=e.target.value;draft.dirty=true;if(key==='mode')q('#mw-schedule').innerHTML=scheduleFields();if(key==='location'){draft.area=draft.location==='downtown'?'Downtown Dubai, United Arab Emirates':draft.location==='marina'?'Dubai Marina, United Arab Emirates':'';renderWizard();}});
  popup.addEventListener('cancel',e=>{e.preventDefault();requestClose();});
  q('#mw-location').addEventListener('change',renderProjects);q('#mw-search').addEventListener('input',renderProjects);
  document.addEventListener('click',e=>{
    const b=e.target.closest('[data-mw-action],[data-mw-filter]');if(!b)return;
    if(b.dataset.mwFilter){filter=b.dataset.mwFilter;renderProjects();return;}
    const a=b.dataset.mwAction,p=b.dataset.mwId?projects.find(x=>x.id===b.dataset.mwId):current;
    if(a==='new')newResearch();if(a==='close')requestClose();if(a==='done')closeModal();if(a==='discard'){draft=null;closeModal();}if(a==='keep')renderWizard();
    if(a==='step'){step=Number(b.dataset.step);renderWizard();}if(a==='back'){step--;renderWizard();}if(a==='next'&&validStep()){step++;renderWizard();}if(a==='start')start();
    if(a==='example'){draft.brief='Find out what nearby competitors are offering for National Day and how we could attract more family orders without putting delivery quality at risk.';draft.title='National Day opportunity';draft.eventDate='2026-12-02';draft.dirty=true;renderWizard();}
    if(a==='add-competitor')competitorEditor();if(a==='edit-competitor')competitorEditor(Number(b.dataset.index));
    if(a==='cancel-competitor'){q('#mw-competitor-editor').innerHTML='';editor=null;}
    if(a==='remove-competitor'){draft.competitors.splice(Number(b.dataset.index),1);draft.dirty=true;q('#mw-competitors').innerHTML=competitorRows();}
    if(a==='save-competitor'){
      const c={name:q('#mw-competitor-name').value.trim(),website:q('#mw-competitor-website').value.trim(),hint:q('#mw-competitor-hint').value.trim()};
      let err=!c.name?'Add the competitor’s name.':'';if(c.website){try{const u=new URL(c.website);if(!['https:','http:'].includes(u.protocol))err='Use a public http or https website address.';}catch{err='Use a full website address, such as https://example.com.';}}
      if(err){q('#mw-competitor-error').hidden=false;q('#mw-competitor-error').textContent=err;return;}
      if(editor===null)draft.competitors.push(c);else draft.competitors[editor]=c;draft.dirty=true;q('#mw-competitors').innerHTML=competitorRows();q('#mw-competitor-editor').innerHTML='';editor=null;
    }
    if(a==='clear'){q('#mw-location').value='all';q('#mw-search').value='';filter='all';renderProjects();}
    if(a==='project'&&p)showProject(p);if(a==='history'&&p)history(p);
    if(a==='pause'){current.schedulePaused=true;renderProjects();showProject(current);toast('Future monitoring paused in this preview. The current update continues.');}
    if(a==='resume'){current.schedulePaused=false;if(current.state==='paused')current.state='review';renderProjects();showProject(current);toast('Future monitoring resumed in this preview.');}
    if(a==='stop'){current.state='stopped';renderProjects();showProject(current);}
    if(a==='retry'){current.state='queued';renderProjects();showProject(current);toast('Update queued in this preview. The previous report is still available.');}
    if(a==='context')simpleDetail('Improve the next report','<div class="mw-field"><label>Event capacity · Downtown</label><p class="mw-detail-intro">Confirm the number of extra orders the team can fulfil, along with preparation and delivery constraints.</p></div><div class="mw-field"><label>Recent channel reports · Marina</label><p class="mw-detail-intro">Add the latest available reporting period through Channels so the report can use current business evidence.</p></div><p class="mw-preview-foot">Design preview: the existing Business Memory and Channels workspaces remain the places to update these records.</p>');
    if(a==='evidence')simpleDetail(b.dataset.mwId==='delivery'?'Delivery readiness evidence':'Customer feedback context',`<p class="mw-detail-intro">${b.dataset.mwId==='delivery'?'Downtown · Channel reporting period: 1–31 Aug 2026. The report should expose preparation, cancellation and order evidence with its definitions and coverage.':'Business Memory · Updated 10 Sep 2026. A real report would show the underlying feedback sources, permitted scope and relevant dates.'}</p><div class="mw-form-tip">${icon('info')}<div><strong>Fictional evidence example</strong><p>This preview illustrates evidence access; it does not contain a retrieved customer record.</p></div></div>`);
    if(a==='report'&&p&&p.date){current=p;window.marketWatchReport.open(p);}
  });
  window.marketWatchPreview={projects,esc,icon,button,popup,body,footer,header,openModal,closeModal,renderProjects,selectedAdvice,getCurrent:()=>current,setView:v=>{view=v;},locations};
  document.querySelectorAll('[data-dialog="monitor"]').forEach(b=>{b.removeAttribute('data-dialog');b.dataset.mwAction='new';b.className='btn btn-primary';b.innerHTML=icon('plus')+' New research';});
  document.querySelectorAll('[data-tab="insights"] span').forEach(s=>{if(s.classList.contains('chip'))s.remove();});
  const originalTab=tab;
  function revealHorizontal(el){
    if(!el)return;let parent=el.parentElement;
    while(parent&&parent!==document.body){
      if(['auto','scroll'].includes(getComputedStyle(parent).overflowX)&&parent.scrollWidth>parent.clientWidth+1){const target=el.getBoundingClientRect(),frame=parent.getBoundingClientRect();if(target.left<frame.left)parent.scrollLeft-=frame.left-target.left+8;else if(target.right>frame.right)parent.scrollLeft+=target.right-frame.right+8;break;}
      parent=parent.parentElement;
    }
  }
  window.marketWatchPreview.revealHorizontal=revealHorizontal;
  function revealActiveTab(){revealHorizontal(document.querySelector('[role="tab"][aria-selected="true"]'));}
  tab=function(name,updateHistory=true){originalTab(name,updateHistory);requestAnimationFrame(revealActiveTab);};
  document.fonts.ready.then(revealActiveTab);
  renderProjects();tab(location.hash.slice(1)||'insights',false);
})();
