export type GrowthIntelligenceErrorCode =
  | "EVIDENCE_SUPPORT_MISSING"
  | "EVIDENCE_SOURCE_DUPLICATE"
  | "EVIDENCE_TIMESTAMP_INVALID"
  | "EVIDENCE_TIME_ORDER_INVALID"
  | "GEOGRAPHY_HIERARCHY_INVALID"
  | "IMPACT_RANGE_INVALID"
  | "IMPACT_CURRENCY_MISMATCH"
  | "PROFILE_VERSION_CONFLICT"
  | "RESEARCH_IDEMPOTENCY_CONFLICT"
  | "RESEARCH_PROVIDER_NOT_QUALIFIED"
  | "RESEARCH_BUDGET_ALLOWANCE_EXCEEDED"
  | "RESEARCH_BUDGET_RESERVATION_EXCEEDED"
  | "RESEARCH_BUDGET_OVERRUN_BLOCKED"
  | "RESEARCH_BUDGET_LEASE_STALE"
  | "RESEARCH_BUDGET_SCOPE_CLOSED"
  | "RESEARCH_BUDGET_CONFLICT"
  | "RESEARCH_BUDGET_UNAVAILABLE";

export class GrowthIntelligenceError extends Error {
  readonly name = "GrowthIntelligenceError";

  constructor(
    public readonly code: GrowthIntelligenceErrorCode,
    message: string,
  ) {
    super(message);
  }
}
